import type { Metadata } from "next";
import NextLink from "next/link";
import type { PropsWithChildren } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <nav>
          <NextLink href="/">Top</NextLink>
          <NextLink href="/about">About</NextLink>
          <NextLink href="/hoge">Hoge</NextLink>
        </nav>
      </body>
    </html>
  );
}
